---
server:
  port: 8761

spring:
  application:
    name: server2
#  profiles: server2


#eureka:
#  instance:
#    hostname: localhost
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
eureka:
  client:
    hostname: server2
    serviceUrl:
      defaultZone: http://server1:8762/eureka/